### ISSUE TITLE
Application Crash : No package identifier when getting value for resource number 0x00000000

### ISSUE THREAD

**Issue by joginder89** [3pillarlabs/socialauth-android#67]
When I call adapter.authorize(SocialSharing.this, SocialAuthAdapter.Provider.TWITTER); or adapter.authorize(SocialSharing.this, SocialAuthAdapter.Provider.LINKEDIN); my application crash with error given No package identifier when getting value for resource number 0x00000000 .

Full Error code is 

Selected provider is linkedin
Loading keys and secrets from configuration
Loading application configuration
Starting webview for authentication
Loading plugins
Loading plugin :: org.brickred.socialauth.plugin.linkedin.FeedPluginImpl
Loading plugin :: org.brickred.socialauth.plugin.linkedin.CareerPluginImpl
Determining URL for redirection
Redirection to following URL should happen : https://api.linkedin.com/uas/oauth/authenticate?oauth_token=75--3fee83bb-2821-4a6a-a8d1-69f64c170da8&oauth_callback=http%3A%2F%2Fsocialauth.in%2Fsocialauthdemo%2FsocialAuthSuccessAction.do
Loading URL : https://api.linkedin.com/uas/oauth/authenticate?oauth_token=75--3fee83bb-2821-4a6a-a8d1-69f64c170da8&oauth_callback=http%3A%2F%2Fsocialauth.in%2Fsocialauthdemo%2FsocialAuthSuccessAction.do&type=user_agent&display=touch
Callback URI : http://socialauth.in/socialauthdemo/socialAuthSuccessAction.do
Resolution X﹕ 1200
Resolution Y﹕ 1824
screeninch﹕ 7
dapi﹕ 320
ResourceType﹕ No package identifier when getting value for resource number 0x00000000

android.content.res.Resources$NotFoundException: Resource ID #0x0
            at android.content.res.Resources.getValue(Resources.java:1266)
            at android.content.res.Resources.getDrawable(Resources.java:785)
            at android.content.res.Resources.getDrawable(Resources.java:752)
            at org.brickred.socialauth.android.SocialAuthDialog.setUpTitle(SocialAuthDialog.java:191)
            at org.brickred.socialauth.android.SocialAuthDialog.onCreate(SocialAuthDialog.java:146)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:373)
            at android.app.Dialog.show(Dialog.java:274)
            at org.brickred.socialauth.android.SocialAuthAdapter$4$1.run(SocialAuthAdapter.java:649)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

There is an method setUpTitle() in SocialAuthDialog class and line 
this.icon = this.getContext().getResources().getDrawable(res); 
have problem.

**Comment by silviahisham** [comment]
same problem here

**Comment by Diwakar1988** [comment]
Looks like you are not having provider name icon in drawable folder, in this case you are using twitter/linkedin provider and system didn't find any twitter/linkedin drawable while trying to create SocialAuthDialog.
Please refer to any sample project for more understanding. Each sample is having all provider icons they are going to use.
