### ISSUE TITLE
Facebook return status not updated. Return Status code :403.

### ISSUE THREAD

**Issue by vgonisanz** [3pillarlabs/socialauth-android#7]
In samples custom-ui and share button, when try to post a message, log returns:

02-05 13:16:39.757: I/FacebookImpl(28375): Updating status : yktjtktk
02-05 13:16:39.917: D/SocialAuthError(28375): org.brickred.socialauth.exception.SocialAuthException: org.brickred.socialauth.exception.SocialAuthException: Status not updated. Return Status code :403
02-05 13:16:39.917: D/Custom-UI(28375): Error
02-05 13:16:39.917: W/System.err(28375): org.brickred.socialauth.android.SocialAuthError: Message Not Posted
02-05 13:16:39.917: W/System.err(28375):    at org.brickred.socialauth.android.SocialAuthAdapter$6.run(SocialAuthAdapter.java:862)
02-05 13:16:39.917: W/System.err(28375):    at java.lang.Thread.run(Thread.java:841)
- Log in is ok.
- Auth app in FB is ok.
- Other calls like User profile works.

**Comment by sohel274** [comment]
Someone tell me what is the final Answer to solve this problem. I am trying it from last 4  months. Now I am tired.

**Comment by agap** [comment]
After I've done everything EXACTLY as mentioned in [Facebook Guide](https://github.com/3pillarlabs/socialauth-android/wiki/Guide-Facebook) mentioned by @vineetmobile the issue disappeared.

**Comment by AnuvadiyaHiren** [comment]
I have resolved issue by upgrading socialauth-4.8.jar file.
Clear app data from setting and login again.

**Comment by Sabari-Karthik3** [comment]
where can i download socailauth-4.8 jar file? @AnuvadiyaHiren

**Comment by Sabari-Karthik3** [comment]
where can i download socailauth-4.8 jar file? @AnuvadiyaHiren

**Comment by Sabari-Karthik3** [comment]
where can i download socailauth-4.8 jar file?

**Comment by Sabari-Karthik3** [comment]
where can i download socailauth-4.8 jar file?

**Comment by Sabari-Karthik3** [comment]
where can i download socailauth-4.8 jar file?

**Comment by Sabari-Karthik3** [comment]
where can i download socailauth-4.8 jar file?

**Comment by Sabari-Karthik3** [comment]
@AnuvadiyaHiren I have downloaded socialauth-4.8 jar from this link liquidtelecom.dl.sourceforge.net/project/socialauth/socialauth-java-sdk-4.8.zip .Even though it is not updating the status in my facebook wall and am getting return status code 400 sometimes and status code 403 sometimes.what may be the problem?

**Comment by Ranjith121** [comment]
I get this same error in my app using socialauth 4.8. and socialauth-android 3.2

org.brickred.socialauth.exception.SocialAuthException: Status not updated. Return Status code :403

Please any one help??
