### ISSUE TITLE
Build error due to org.apache.xerces classes in preDex phase

### ISSUE THREAD

**Issue by mahendranv** [3pillarlabs/socialauth-android#85]
**EDIT** : Using Gradle 2.11 causing builds to failure. Whereas Gradle 2.2 works fine.

I've just cloned the repo and tried to run sharebar sample in AndroidStudio.

I got exception saying 

`
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
    at com.android.dx.command.dexer.Main.processClass(Main.java:752)
    at com.android.dx.command.dexer.Main.processFileBytes(Main.java:718)
    at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
    at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1645)
    at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    at com.android.dx.command.dexer.Main.processOne(Main.java:672)
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:574)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)
Caused by: com.android.dx.cf.iface.ParseException: bad utf-8 byte a0 at offset 00000004
    at com.android.dx.cf.cst.ConstantPoolParser.parseUtf8(ConstantPoolParser.java:374)
    at com.android.dx.cf.cst.ConstantPoolParser.parse0(ConstantPoolParser.java:262)
    at com.android.dx.cf.cst.ConstantPoolParser.parse0(ConstantPoolParser.java:294)
    at com.android.dx.cf.cst.ConstantPoolParser.parse(ConstantPoolParser.java:150)
    at com.android.dx.cf.cst.ConstantPoolParser.parseIfNecessary(ConstantPoolParser.java:124)
    at com.android.dx.cf.cst.ConstantPoolParser.getPool(ConstantPoolParser.java:115)
    at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:482)
    at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
    at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
    at com.android.dx.command.dexer.Main.parseClass(Main.java:764)
    at com.android.dx.command.dexer.Main.access$1500(Main.java:85)
    at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1684)
    at com.android.dx.command.dexer.Main.processClass(Main.java:749)
    ... 12 more
Caused by: java.lang.IllegalArgumentException: bad utf-8 byte a0 at offset 00000004
    at com.android.dx.rop.cst.CstString.throwBadUtf8(CstString.java:171)
    at com.android.dx.rop.cst.CstString.utf8BytesToString(CstString.java:143)
    at com.android.dx.rop.cst.CstString.<init>(CstString.java:200)
    at com.android.dx.cf.cst.ConstantPoolParser.parseUtf8(ConstantPoolParser.java:371)
    ... 25 more
1 error; aborting
`

And I believe some of the trasitive dependencies  are colliding with android core classes.
- commons-logging:commons-logging:1.1.1
- org.json:json:20090211

I thought the xerces dependency is build using old java version and built it manually.
So I've cloned 'xerces' from apache svn and build a jar. Added the same to libs directory. Also excluded logging & json dependencies.
my final build dependencies in :socialauthandroid looks like this
`
compile fileTree(include: ['*.jar'], dir: 'libs')
compile('org.brickred:socialauth:4.12') {
        exclude module: 'org.apache.xerces'
        exclude group:'commons-logging', module:'commons-logging'
        exclude group:'org.json', module:'json'
}
`

Still getting error as follows.

`
trouble processing "javax/xml/XMLConstants.class":
Ill-advised or mistaken usage of a core class (java.* or javax.*)
when not building a core library.
`

**Comment by silviahisham** [comment]
+1

**Comment by devnull69** [comment]
You can use jarjar with a rules file like

rule javax.xml.*\* your.package.name.xml.@1

to repackage the javax core library files in your xml-apis-x.x.xx.jar and all of its depending jars (like xalan-serializer etc.)

Please keep us posted about your progress because I'm currently struggling with the same issue using xalan (which has a depedency to xerces)

**Comment by MassimoCappellano** [comment]
Hi,

I had the same problem and for a try, I've excluded even `xml-apis` and `xercesImpl`

```
compile ('org.brickred:socialauth:4.12'){
        exclude module: 'org.apache.xerces'
        exclude group:'commons-logging', module:'commons-logging'
        exclude group:'org.json', module:'json'
        exclude group:'xml-apis', module:'xml-apis'
        exclude group:'xerces', module:'xercesImpl'
    }
```

It works inside android studio, deploying customui on emulator, but not from command line, running `gradle build` or `gradlew build`:

```
Note: org.brickred.socialauth.util.HttpUtil accesses a field 'SDK_INT' dynamical
ly
      Maybe this is library field 'android.os.Build$VERSION { int SDK_INT; }'
Note: org.cyberneko.html.HTMLConfiguration accesses a field 'fVersion' dynamical
ly
Note: there were 7 references to unknown classes.
      You should check your configuration for typos.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)

Note: there were 2 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclas
s)
Note: there were 6 class casts of dynamically created class instances.
      You might consider explicitly keeping the mentioned classes and/or
      their implementations (using '-keep').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclas
scast)
Note: there were 2 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclas
smember)
Warning: there were 1575 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolved
class)
Warning: there were 21 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolved
programclassmember)
Warning: Exception while processing task java.io.IOException: Please correct the
 above warnings first.
:customui:transformClassesAndResourcesWithProguardForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':customui:transformClassesAndResourcesWithProguardFor
Release'.
> java.io.IOException: Please correct the above warnings first.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 1 mins 41.583 secs

C:\proof_react_native3\socialauth-android>
```

I think my is a workaroud, but not correct. I'm totally new to android development. 
Thanks for the very interesting explanations above.
