### ISSUE TITLE
ResourceNotFoundException on authorizing adapter

### ISSUE THREAD

**Issue by silviahisham** [3pillarlabs/socialauth-android#88]
I get this error on authorizing the `SocialAuthAdapter` with facebook, I'm using socialauth-4.11.jar 
`mSocialAuthAdapter.authorize(mCtx, SocialAuthAdapter.Provider.FACEBOOK);`

**Stack trace:**
`FATAL EXCEPTION: main
android.content.res.Resources$NotFoundException: Resource ID #0x0
    at android.content.res.Resources.getValue(Resources.java:1233)
    at android.content.res.Resources.getDrawable(Resources.java:756)
    at android.content.res.Resources.getDrawable(Resources.java:724)
    at org.brickred.socialauth.android.SocialAuthDialog.setUpTitle(SocialAuthDialog.java:191)
    at org.brickred.socialauth.android.SocialAuthDialog.onCreate(SocialAuthDialog.java:146)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:373)
    at android.app.Dialog.show(Dialog.java:274)
    at org.brickred.socialauth.android.SocialAuthAdapter$4$1.run(SocialAuthAdapter.java:649)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)`

**Comment by Diwakar1988** [comment]
Looks like you are not having provider name icon in drawable folder, in this case you are using facebook provider and system didn't find any facebook  drawable while trying to create SocialAuthDialog.
Please refer to any sample project for more understanding. Each sample is having all provider icons they are going to use.
